# Generated by Django 2.2.6 on 2019-12-16 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_auto_20191216_2020'),
        ('homework', '0003_auto_20191216_2020'),
        ('question_lib', '0002_auto_20191216_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCondition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_score', models.IntegerField()),
                ('submit_answer', models.TextField(blank=True, max_length=500)),
                ('status', models.IntegerField(choices=[(0, '未完成'), (1, '已完成')], default=0)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0)),
                ('homework_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.Homework')),
                ('question_lib_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_lib.QuestionLib')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
            options={
                'db_table': 'question_condition',
            },
        ),
    ]
