# Generated by Django 2.2.6 on 2020-01-08 03:27

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_auto_20191216_2020'),
        ('student', '0004_trueclass'),
        ('homework_condition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='questioncondition',
            managers=[
                ('question_condition_manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='questioncondition',
            name='question_score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='HomeworkCondition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, '未完成'), (1, '已完成')], default=0)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0)),
                ('homework_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.Homework')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
            options={
                'db_table': 'homework_condition',
            },
        ),
    ]
