# Generated by Django 2.2.6 on 2020-01-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_condition', '0002_auto_20200108_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncondition',
            name='submit_answer',
            field=models.TextField(max_length=500),
        ),
    ]
