# Generated by Django 2.2.6 on 2019-12-12 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('homework_name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('homework_score', models.CharField(max_length=128)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0)),
            ],
            options={
                'db_table': 'homework',
            },
        ),
        migrations.CreateModel(
            name='HomeworkQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('homework_question_score', models.CharField(max_length=128)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0)),
                ('homework_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.Homework')),
            ],
            options={
                'db_table': 'homework_question',
            },
        ),
    ]
