# Generated by Django 2.2.6 on 2019-12-16 20:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_auto_20191212_2253'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='homework',
            managers=[
                ('homework_manage', django.db.models.manager.Manager()),
            ],
        ),
    ]
