# Generated by Django 2.2.6 on 2019-12-16 20:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('student_manage', django.db.models.manager.Manager()),
            ],
        ),
    ]
