# Generated by Django 2.2.6 on 2019-12-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20191216_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_college',
            field=models.IntegerField(choices=[(0, '信息科学与工程学院'), (1, '法学院'), (2, '政治学与公共管理学院'), (3, '计算机科学与技术学院'), (4, '生命科学学院'), (5, '环境科学与工程学院')], default=0),
        ),
    ]
