# Generated by Django 2.2.6 on 2019-12-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20191220_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrueClass',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('true_class', models.CharField(max_length=128, unique=True)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0)),
            ],
            options={
                'db_table': 'true_class',
            },
        ),
    ]
