# Generated by Django 2.2.6 on 2020-01-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_trueclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_college',
            field=models.CharField(max_length=128),
        ),
    ]
