# Generated by Django 2.2.6 on 2019-12-09 17:20

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('vir_class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=128)),
                ('course_location', models.CharField(max_length=255)),
                ('course_time', models.CharField(max_length=128)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vir_class.VirClass')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Teacher')),
            ],
            options={
                'db_table': 'course',
            },
            managers=[
                ('course_manage', django.db.models.manager.Manager()),
            ],
        ),
    ]
