# Generated by Django 2.2.6 on 2019-12-16 20:20

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('question_lib', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='questionlib',
            managers=[
                ('question_lib_manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='questionlib',
            name='question_type',
            field=models.IntegerField(choices=[(0, '单选'), (1, '多选'), (2, '判断'), (3, '编程')], default=3),
        ),
    ]
