# Generated by Django 2.2.6 on 2019-12-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_lib', '0002_auto_20191216_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlib',
            name='answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='questionlib',
            name='content',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='questionlib',
            name='question_type',
            field=models.IntegerField(choices=[(0, '单选题'), (1, '多选题'), (2, '判断题'), (3, '编程题')], default=3),
        ),
    ]
