# Generated by Django 2.2.6 on 2019-12-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_lib', '0003_auto_20191217_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlib',
            name='question_score',
            field=models.IntegerField(default=0),
        ),
    ]
