# Generated by Django 2.2.6 on 2019-12-17 17:20

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='image_db')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'image',
            },
            managers=[
                ('image_manage', django.db.models.manager.Manager()),
            ],
        ),
    ]
