# Generated by Django 2.2.6 on 2020-01-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20191220_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_college',
            field=models.CharField(max_length=128),
        ),
    ]
